### ISSUE TITLE
BTP account URL for not working

### ISSUE THREAD

**Issue by ankur-babu** [ilyabelozerovsap/btp-end-to-end-scenario-use-cases#1]
I am trying to access BTP Account with url https://url.sap/uj3hi8 but I am not able to find it after I login with my SAP Universal ID and Password. I didn't receive any email to access this account also.

S/4HANA Cloud system is working fine for me and I was able to finish exercise 1-4 using it.

Can someone help me with this?

**Comment by ilyabelozerovsap** [comment]
Could you please try [this URL](https://emea.cockpit.btp.cloud.sap/cockpit#/globalaccount/a9030b2a-ed51-438e-9166-241ce6c0291d/subaccount/a4dcf351-0d4c-463a-a908-7285b11bb527/subaccountoverview)

And log on with the same credentials as you use for S4HANA Cloud.

**Comment by ankur-babu** [comment]
Unfortunately, still not working. I have two other S-User ID linked to my Universal SAP ID and when I login with same credentials as S/4HANA Cloud, it says it cannot find the Account I am looking for but just show my other BTP Accounts.

**Comment by ilyabelozerovsap** [comment]
This is strange. We have your email ank##.ba##@beari##point.com in the IAS system. So please make sure that you are logged-in with this email. 

Have you been asked on logon which IDP should be used? You need to use pesworkshop 
Maybe with [this link ](https://emea.cockpit.btp.cloud.sap/cockpit/?idp=pesworkshops.accounts.ondemand.com#/globalaccount/a9030b2a-ed51-438e-9166-241ce6c0291d/subaccount/a4dcf351-0d4c-463a-a908-7285b11bb527/subaccountoverview) it will work correct.

**Comment by ankur-babu** [comment]
It is working now, thank you. I tried with the new link which you provided.
